### PR TITLE
Add support for configuring startup_states on minion

### PR DESCRIPTION
**Pull request by tmclaugh-jana**

### CODE REVIEW

**Comment by tmclaugh-jana** [comment]
Maybe this is a bad idea?  Not familiar enough with salt to know.  I'm just migrating our config management to Puppet while leaving Orchestration to be handled by Salt.

**Comment by aboe76** [comment]
No, not a bad idea, if the option is available in the minion config and it can be set, it should be possible to manage. As long as it isn't applied by default but explicitly set.

I will test it before before i merge this, later today.

**Comment by aboe76** [comment]
@tmclaugh-jana thanks

**Comment by tmclaugh** [comment]
Just for reference, that ghost account was my employer specific account.  Back to this one finally.  Thanks for the merge!

**Comment by aboe76** [comment]
No problem,

**Pull request merged**
